AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  my_first_sam

  Sample SAM Template for my_first_sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Environment:
      Variables:
        bmrs_key: !Ref Key

Parameters:
  Key:
    Type: String
    Description: BMRS API key
    Default: default value

Resources:
  DataCaptureFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: datacapture/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - DynamoDBWritePolicy:
            TableName: coal
      Events:
        DataCapture:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /datacapture
            Method: get
        DailyRun:
          Type: Schedule
          Properties:
            Schedule: cron(24 19 * * ? *)
            Enabled: True

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DataCaptureApi:
    Description: "API Gateway endpoint URL for Prod stage data capture function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/datacapture/"
  DataCaptureFunction:
    Description: "Data capture Lambda Function ARN"
    Value: !GetAtt DataCaptureFunction.Arn
  DataCaptureFunctionIamRole:
    Description: "Implicit IAM Role created for data capture function"
    Value: !GetAtt DataCaptureFunctionRole.Arn
